import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Abhaya_Libre, Abril_Fatface, Aleo, Fjalla_One, Merriweather_Sans, Poller_One } from 'next/font/google'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const abril_fatface = Abril_Fatface({ weight: ['400'], subsets: ['latin'], variable: '--font-abril_fatface' })
const abhaya_libre = Abhaya_Libre({ weight: ['400', '500', '700'], subsets: ['latin'], variable: '--font-abhaya_libre' })
const aleo = Aleo({ weight: ['400'], subsets: ['latin'], variable: '--font-aloe' })
const fjala_one = Fjalla_One({ weight: '400', subsets: ['latin'], variable: '--font-fjala_one' })
const merriweather_sans = Merriweather_Sans({ weight: '400', subsets: ['latin'], variable: '--font-merriwheather_sans' })
const poller = Poller_One({ weight: ['400'], subsets: ['latin'], variable: '--font-poller' })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${abril_fatface.variable} ${abhaya_libre.variable} ${aleo.variable} ${fjala_one.variable} ${merriweather_sans.variable} ${poller.variable}`}>
      <body className="overflow-x-hidden">
        <Header />
        {children}
      </body>
    </html>
  )
}
